name: Build Run4Ever

on:
  push:
    branches: [ "master" ]

env:
  DOCKER_IMG: mparvin/run4ever

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_IMG:${{ github.sha }}
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Push the Docker image
      run: docker push $DOCKER_IMG:${{ github.sha }}

    - name: Push to Docker registry with latest tag
      run: docker tag $DOCKER_IMG:${{ github.sha }} $DOCKER_IMG:latest && docker push $DOCKER_IMG:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/username/repository:latest

    - name: Add github release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          run4ever
        draft: true
        prerelease: true
        tag_name: ${{ github.sha }}
        name: ${{ github.sha }}
        body: ${{ github.sha }}
